f=open('春雪.txt','w')
f.write('xinnianduweiyoufanhua\neryuechujingxiancaoya\nbaixuequexianchunsewan\nguchuantingshuzuofeihua.\n')
f.writelines(['1','2','3','4'])
f.write('haha')
f.writelines(['5','6','7','8'])
f.close()
